#!/usr/bin/env python3
"""Export PREMIS and raw JSON only for crawl configs that are new or changed.

Compares the previously committed overview Markdown table (``data/README.md``,
generated by ``btc2premis --list --format markdown``) against a freshly fetched
one. A crawl config is (re-)exported with ``btc2premis -c <cid> --emit both
--output-dir <output-dir>`` only if it is new or if one of ``crawls``,
``lastCrawl``, ``lastState``, ``modified`` or ``rev`` changed. Crawl configs
that disappeared from the current overview have their PREMIS and raw JSON
files removed.

The row-based diff only looks at the plain data columns (``cid`` and
``CHANGE_COLUMNS``); the ``json``/``premis-xml`` link columns are ignored, so
adding or changing links does not by itself trigger a re-export.

Used by ``.github/workflows/crawl-export.yml``; not part of the installed
``btc2premis`` package.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

CHANGE_COLUMNS = ("crawls", "lastCrawl", "lastState", "modified", "rev")
PREMIS_XML_SUBDIR = "premis/xml"
JSON_SUBDIR = "json"


def read_markdown_table(path: Path) -> dict[str, dict[str, str]]:
    """Parse the pipe-delimited overview table written by ``--format markdown``.

    Only lines starting with ``|`` are considered; the first one is the header,
    the second (the ``---`` separator) is skipped, all following ones are data
    rows. This is deliberately simple (no support for escaped pipes within
    cells) since the overview table only ever contains plain text and links.
    """
    if not path.exists():
        return {}

    def split_row(line: str) -> list[str]:
        return [cell.strip() for cell in line.strip().strip("|").split("|")]

    rows: dict[str, dict[str, str]] = {}
    headers: list[str] | None = None
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.strip().startswith("|"):
            continue
        cells = split_row(line)
        if headers is None:
            headers = cells
            continue
        if all(set(cell) <= {"-", ":"} for cell in cells):
            continue  # separator row (---|---|...)
        row = dict(zip(headers, cells, strict=False))
        cid = row.get("cid")
        if cid:
            rows[cid] = row
    return rows


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--previous", required=True, type=Path)
    parser.add_argument("--current", required=True, type=Path)
    parser.add_argument("--output-dir", required=True, type=Path)
    args = parser.parse_args(argv)

    previous = read_markdown_table(args.previous)
    current = read_markdown_table(args.current)

    changed = [
        cid
        for cid, row in current.items()
        if cid not in previous
        or any(row.get(col, "") != previous[cid].get(col, "") for col in CHANGE_COLUMNS)
    ]
    removed = [cid for cid in previous if cid not in current]

    print(
        f"{len(current)} crawl config(s) total, {len(changed)} new/changed, {len(removed)} removed."
    )

    for cid in changed:
        print(f"Exporting {cid} ({current[cid].get('name', '')})")
        subprocess.run(
            ["btc2premis", "-c", cid, "--emit", "both", "--output-dir", str(args.output_dir)],
            check=True,
        )

    for cid in removed:
        for subdir, suffix in ((PREMIS_XML_SUBDIR, "xml"), (JSON_SUBDIR, "json")):
            target = args.output_dir / subdir / f"{cid}.{suffix}"
            if target.exists():
                print(f"Removing {target} (crawl config no longer present)")
                target.unlink()

    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
